version: '3.7'

services:
  app:
    container_name: it-logger
    command: npm start
    restart: always
    build: .
    volumes:
      - '.:/usr/app'
      - '/usr/app/node_modules'
    ports:
      - 5000:5000
    environment:
      - CHOKIDAR_USEPOLLING=true
